spring.application.name=DockerTraining
spring.datasource.url=jdbc:postgresql://localhost:5431/treinodocker
spring.datasource.username=postgres
spring.datasource.password=postgres
datasource.driver-class-name=org.postgresql.Driver

# Configuração do Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true